[package]
name = "ludared"
version = "0.1.0"
edition = "2024"

authors = ["Arnaud 'red' Rouyer"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/joshleaves/ludared"
repository = "https://github.com/joshleaves/ludared"

exclude = ["tests/**"]

[[bin]]
name = "ludared"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
hex = "0.4.3"
log = "0.4.33"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
stderrlog = "0.6.0"
toml = "1.1.2"

[profile.dev]
debug = "line-tables-only"
split-debuginfo = "unpacked"

[profile.dev.package."*"]
debug = false
